file=open('C:/Users/HP/Downloads/python programmes/hello.txt','r')
print(file.read())
file.close()
file.close()
file=open('C:/Users/HP/Downloads/python programmes/hello.txt','r')
print("\n Read in parts \n")
print(file.read(8))
file.close()
file=open('C:/Users/HP/Downloads/python programmes/hello.txt','a')
file.write(". Hi!, i am a penguin and I am 1 years old.")
file.close()
file_write=open('C:/Users/HP/Downloads/python programmes/hellonew.txt','w')
file_write.write("File in write mode .........")
file_write.write(". Hi!, i am a penguin and I am 1 years old.")
file_write.close()
file=open('C:/Users/HP/Downloads/python programmes/hello.txt','r')
print(file.readline())
file.close()

