
CREATE TABLE IF NOT EXISTS NOBEL_WIN (
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGORY TEXT
);


INSERT INTO NOBEL_WIN VALUES
(1970,'PHYSICS','HANNES ALFVEN','SWEDEN','SCIENTIST'),
(1970,'PHYSICS','LOUIS NEEL','SWEDEN','SCIENTIST'),
(1971,'PHYSICS','PAUL','FRANCE','SCIENTIST'),
(1971,'CHEMISTRY','HAMILITON','SWEDEN','LINGUIST'),
(1972,'LITERATURE','BERNARD KELSON','GERMANY','ECONOMIST'),
(1972,'ECONOMICS','JOSEPH','RUSSIA','ECONOMIST'),
(1973,'BIOLOGY','PHILIPS','USA','PRIME MINISTER'),
(1980,'BIOLOGY','MARTIN','USA','PRIME MINISTER'),
(1981,'PHYSIOLOGY','HANNAH','HUNGARY','SCIENTIST'),
(1975,'PHYSICS','PETER','CHILE','SCIENTIST');


SELECT * 
FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';